import { 
  LayoutDashboard, 
  ShoppingCart, 
  Users, 
  Store, 
  Car, 
  Tag, 
  Wallet, 
  History,
  Map,
  MapPin,
  List,
  MessageSquare,
  Scale,
  ShieldAlert,
  Package,
  Star,
  Search,
  Bell,
  FileText,
  Shield,
  Settings
} from 'lucide-react';

export const navigation = [
  { name: 'الرئيسية', href: '/', icon: LayoutDashboard, group: 'الرئيسية' },
  { name: 'الطلبات', href: '/orders', icon: ShoppingCart, group: 'إدارة الطلبات' },
  { name: 'المنتجات', href: '/products', icon: Package, group: 'إدارة الطلبات' },
  { name: 'التقييمات', href: '/reviews', icon: Star, group: 'إدارة الطلبات' },
  { name: 'العملاء', href: '/users', icon: Users, group: 'إدارة المستخدمين' },
  { name: 'المسؤولين', href: '/admins', icon: Shield, group: 'إدارة المستخدمين' },
  { name: 'التجار', href: '/vendors', icon: Store, group: 'إدارة المستخدمين' },
  { name: 'السائقين', href: '/drivers', icon: Car, group: 'إدارة المستخدمين' },
  { name: 'المالية والمحافظ', href: '/finance', icon: Wallet, group: 'المالية' },
  { name: 'المعاملات المالية', href: '/finance/transactions', icon: History, group: 'المالية' },
  { name: 'المناطق والتوصيل', href: '/zones', icon: Map, group: 'المناطق والتصنيفات' },
  { name: 'المدن', href: '/cities', icon: MapPin, group: 'المناطق والتصنيفات' },
  { name: 'التصنيفات', href: '/categories', icon: List, group: 'المناطق والتصنيفات' },
  { name: 'الدعم الفني', href: '/support', icon: MessageSquare, group: 'الدعم والنزاعات' },
  { name: 'محادثات الدعم', href: '/support/chats', icon: MessageSquare, group: 'الدعم والنزاعات' },
  { name: 'فض النزاعات', href: '/disputes', icon: Scale, group: 'الدعم والنزاعات' },
  { name: 'الجزاءات', href: '/penalties', icon: ShieldAlert, group: 'الدعم والنزاعات' },
  { name: 'العروض الترويجية', href: '/promotions', icon: Tag, group: 'التسويق والتقارير' },
  { name: 'سجل البحث', href: '/search-history', icon: Search, group: 'التسويق والتقارير' },
  { name: 'الإشعارات', href: '/notifications', icon: Bell, group: 'التسويق والتقارير' },
  { name: 'التقارير', href: '/reports', icon: FileText, group: 'التسويق والتقارير' },
  { name: 'سجل العمليات', href: '/audit', icon: History, group: 'النظام والإعدادات' },
  { name: 'الصلاحيات', href: '/permissions', icon: Shield, group: 'النظام والإعدادات' },
  { name: 'الإعدادات', href: '/settings', icon: Settings, group: 'النظام والإعدادات' },
];
